### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by 4dvn** [golimarrrr/fix-3gp#1]
How can i compile it on windows, my mov, mp4, wav files was encrypted by ransomware 150kb of header and 334 bytes added from the end of files

**Comment by golimarrrr** [comment]
I don't think it will help if the files are encrypted by ransomware. Anyway it should compile fine with any Windows GCC implementation. Just tried with Cygwin GCC and it works

**Comment by 4dvn** [comment]
> I don't think it will help if the files are encrypted by ransomware. Anyway it should compile fine with any Windows GCC implementation. Just tried with Cygwin GCC and it works

How can i repair it with audio file, i just remove all 0-153604 bytes from corrupt file and copy the offset 0-20 of good file and adding 153604 bytes zero and merger the last data of corrupt file and remove 334 bytes from end of file of corrupt file

**Comment by golimarrrr** [comment]
Audio file should be the same as video file. Did you compile and use the tool against your file?

**Comment by 4dvn** [comment]
Yes, i compiled but audio file not work with that :(---- On Tue, 26 May 2020 18:34:50 +0700  notifications@github.com<notifications@github.com> wrote ---- 
Audio file should be the same as video file. Did you compile and use the tool against your file?

**Comment by golimarrrr** [comment]
You can try to upload the file and post the link to see if someone can help. Did you try https://github.com/ponchio/untrunc ?
